url: "https://cilj.github.io"
project_name: Cilj Project
project_tagline: goals
twitter_username: CiljProject
github_username:  cilj

theme: jekyll-theme-cayman

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
# gems:
#   - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
